name: Sync Files from External Repositories

on:
#  /*schedule:
#    - cron: '0 0 * * *'  # 每天午夜触发一次
  workflow_dispatch:  # 手动触发
#  push:
#    branches:
#      - master  # 当 master 分支有更新时也触发

jobs:
  sync_files:
    runs-on: ubuntu-latest

    steps:
      # 步骤 1：检出当前仓库的代码
      - name: Checkout current repository
        uses: actions/checkout@v2

      # 步骤 2：从第一个仓库拉取文件 (check_sudo.sh)
      - name: Checkout first repository (check_sudo.sh)
        uses: actions/checkout@v2
        with:
          repository: 'zjk2017/ArcadiaScriptPublic'  # 拉取第一个仓库
          ref: 'main'  # 如果目标仓库不是主分支，修改为对应分支
          path: repo1  # 拉取到 repo1 目录

      # 步骤 3：从第一个仓库复制文件到目标文件夹
      - name: Copy check_sudo.sh to target folder
        run: |
          cp repo1/yidongyunpan.py ./
          rm -rf repo1

      - name: Configure Git user for Actions
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@users.noreply.github.com"

      # 步骤 8：提交并推送更改
      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Sync files from external repositories"
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub token 进行身份验证
